# Generated by Django 4.1 on 2022-08-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_remove_produto_nompreco_marketing_promocional_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
        migrations.AlterField(
            model_name='variacao',
            name='preco',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='variacao',
            name='preco_promocional',
            field=models.FloatField(default=0, verbose_name='Preço promocional'),
        ),
    ]
